openapi: 3.0.0
info:
  title: vet-ticket-api
  version: 1.0.0
paths:
  /ticket/{appointmentId}:
    get:
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: <FUNCTION_ID>
        service_account_id: <SERVICE_ACCOUNT_ID>
        payload_format_version: "0.1"
      responses:
        '302':
          description: Redirect to PDF
